version: '3'
services:
        stepik:
                build:
                        context: .
                ports:
                        - 9080:80
                volumes:
                        - .:/home/box/web
